# -*- coding: utf-8 -*-
"""
/***************************************************************************
 StepOne
                                 A QGIS plugin
 Maybe this time Qt5 wont suddenly fail
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-05-24
        copyright            : (C) 2024 by me
        email                : mercerraa@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load StepOne class from file StepOne.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .step1 import StepOne
    return StepOne(iface)
