# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BIPbygg2Fast
                                 A QGIS plugin
 Connects each byggnad to the associated property 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-07-11
        copyright            : (C) 2024 by Andrew Mercer
        email                : mercerraa@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load BIPbygg2Fast class from file BIPbygg2Fast.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .bip_b2f import BIPbygg2Fast
    return BIPbygg2Fast(iface)
