# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AggregateCentroids
                                 A QGIS plugin
 Creates centroids of attribute aggregates
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-05-31
        copyright            : (C) 2024 by Andrew Mercer
        email                : https://github.com/mercerraa
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load AggregateCentroids class from file AggregateCentroids.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .aggregate_centroids import AggregateCentroids
    return AggregateCentroids(iface)
